# -*- coding: utf-8 -*-
"""README.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABNxw7H6RebYjxk5v-ipGUlulL3IX4yD

# Python Essential
### AdTrans project, 2023-1-PL01-KA220-HED-000158917

(June 2025 - IPCA)

Notebook Template for the course

by [*lufer*](mailto:lufer@ipca.pt)

(ver 1.0)

---

### Python Essential Course Material


### |-Scripts
	|- src
		scripts python (modules)
	|- Packages
		|-Calculator
			python package with Divide.py
		|-Many
			python package with Divide.py and Animals.py
			|-Animals.py
				module with Class Animal
	|-docs
		|-html
			index.html
				Documentation generated by doxygen
###|-Practice
	Practical laboratories

###|-Colab Notebooks
	Google Colab notebooks

###|-Python Notebooks
	python equivalentto Google Colab notebboks

###|-Auxiliary material
	Auxiliary documentation

###|-Slides
	Supporting slides

--------------------------------

by lufer
June. 2025
"""