# -*- coding: utf-8 -*-
"""1_Environment_Essential.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0dD9RenfENGPxFuLbZ_-ktHDm6Ee33_

# Python Essential
### AdTrans project, 2023-1-PL01-KA220-HED-000158917

(June 2025 - IPCA)

Notebook (**1_Environment_Essential.ipynb**)

by [*lufer*](mailto:lufer@ipca.pt)

(ver 1.0)

---

# I - Environment


*   This part explores the main considerations about the envionment preparation to work with python  


**Contents**:

0. **Python**
1. **GitHub**
2. **Jupiter Notebooks**
3. **Check Environment**

## 0 - Python

1. Interpreter Instalation

- Download [Python]( python.org)
- Install python
- [Steps to Install]( https://phoenixnap.com/kb/how-to-install-python-3-windows)

\
2. All modules Instalation

- Download  [Anaconda](https://www.anaconda.com/download)
- Install Anaconda
- [Steps to Install](https://www.anaconda.com/docs/getting-started/anaconda/install)

## 1 - GitHub


1.   Create account
2.   Create Repository
3.   Use the repository

## 2 - Jupiter Notebboks

1. Google Colab
2. Creating Jupyter Notebboks
3. Synchronizing with Github


> Installing Jupyter in Windows


```
#install
c:\ pip install jupyter

#running a jupyter notebbok
c:\ python -m jupyterlab

#or
c:\python -m notebook

#or
c:\ python -m pip install jupyter --user
c:\ jupyter notebook
```

## 3 - Check the Environment

Verify if python is installed; check the drive for notebooks files;
"""

#install phyton
#check if python is installed
!python --version # Python >= 3.9.18?

#in Windows
#c:\python --version

"""### Mounting Google Drive"""

# or
#see https://towardsdatascience.com/different-ways-to-connect-google-drive-to-a-google-colab-notebook-pt-1-de03433d2f7a
#see https://adriandolinay.medium.com/an-introduction-to-google-colab-2023-6c26792827b3

from google.colab import drive

# it will ask for your google drive credentiaals
drive.mount('/content/AdTrans', force_remount=True)

#Check the contents
!ls "/content/AdTrans/"

"""### Unmounting Google Drive"""

#see https://www.geeksforgeeks.org/unmount-drive-in-google-colab-and-remount-to-another-drive/

from google.colab import drive
drive.flush_and_unmount()

"""## References

* Install python in windows : https://phoenixnap.com/kb/how-to-install-python-3-windows

* Getting Started with Google Colab: A Beginner's Guide - https://www.marqo.ai/blog/getting-started-with-google-colab-a-beginners-guide

* Install Jupyter in Windows - https://jupyter.org/install

End!
"""