# -*- coding: utf-8 -*-
"""3_Programming_Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JX5z7yDLdk17ZQOiEYrjyPYxughzoNyk

# Python Essential
### AdTrans project, 2023-1-PL01-KA220-HED-000158917

(June 2025 - IPCA)

Notebook (3_Programming_Python.ipynb)

by [*lufer*](mailto:lufer@ipca.pt)

(ver 1.0)

---

Mounting Google drive
"""

# or
#see https://towardsdatascience.com/different-ways-to-connect-google-drive-to-a-google-colab-notebook-pt-1-de03433d2f7a
#see https://adriandolinay.medium.com/an-introduction-to-google-colab-2023-6c26792827b3

from google.colab import drive

# it will ask for your google drive credentiaals
drive.mount('/content/AdTrans/', force_remount=True)

"""### Unmounting Google Drive"""

#if necessary!

from google.colab import drive
drive.flush_and_unmount()

"""[How to unmount](https://www.geeksforgeeks.org/unmount-drive-in-google-colab-and-remount-to-another-drive/)

## Packages
"""

!ls "/content/AdTrans/MyDrive/Colab Notebooks/AdTrans - PE-2025/Calculator"

import sys

# Append the *parent* directory of Calculator/
sys.path.append('/content/AdTrans/MyDrive/Colab Notebooks/AdTrans - PE-2025') # the current working directory

from Calculator import divide, safe_divide

print(divide(20, 4))         # ➜ 5.0
#print(safe_divide(10, 0))    # ➜ "Error: Division by zero."

import Calculator
a = Calculator.divide(20, 4)
a

"""## Modules

* File with python code
* Can include several functions or classes

```
# Identify the header of each module (python file)
'''!
@brief Short description of the module
@author lufer (lufer@ipca.pt)
@date June 2, 2025
'''
```

[See "Divide.py"](https://drive.google.com/file/d/1I9TEG81Ge3MsvpIlTURClrU3Tc4qTUXE/view?usp=sharing)

## Libraries

Collection of modules, functions, and classes that provide reusable code to solve specific tasks
"""

import math #import math library
a=math.sqrt(25)
a

import math as m  #alias
a=m.sqrt(25)
a

dir(math) #show existing functions

from math import sqrt
a = sqrt(25)
a

"""### Functions"""

def my_function():
  print("Hello from a function")

my_function()

def reverse_str(s):
  """Invert the string value"""
  #return s[::-1]
  #or
  return(''.join(reversed(s)))

reverse_str("Benfica is Great")

help(reverse_str)

"""## Classes

[link text](https://)

## References

*   Free Python Courses by Cisco -
https://www.netacad.com/learning-collections/python

End!
"""